project_name: lottery-optimizer

builds:
  - binary: lottery-optimizer
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - lottery-optimizer.yaml.example

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

release:
  github:
    owner: cccarv82
    name: milhoes 