// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {main} from '../models';
import {models} from '../models';

export function CheckAllPendingResults():Promise<Record<string, any>>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function CheckGameResult(arg1:string):Promise<Record<string, any>>;

export function ClearOldNotifications(arg1:number):Promise<Record<string, any>>;

export function DeleteSavedGame(arg1:string):Promise<Record<string, any>>;

export function GenerateStrategy(arg1:main.UserPreferences):Promise<main.StrategyResponse>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetCurrentConfig():Promise<Record<string, any>>;

export function GetCurrentVersion():Promise<string>;

export function GetDashboardSummary():Promise<Record<string, any>>;

export function GetDefaultConfig():Promise<main.ConfigData>;

export function GetNextDraws():Promise<Record<string, any>>;

export function GetNotifications(arg1:number,arg2:boolean):Promise<Record<string, any>>;

export function GetNumberFrequencyAnalysis(arg1:string):Promise<Record<string, any>>;

export function GetPerformanceMetrics():Promise<Record<string, any>>;

export function GetROICalculator(arg1:number,arg2:string):Promise<Record<string, any>>;

export function GetSavedGames(arg1:models.SavedGamesFilter):Promise<Record<string, any>>;

export function GetStatistics():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function MarkNotificationAsRead(arg1:string):Promise<Record<string, any>>;

export function SaveConfig(arg1:main.ConfigData):Promise<Record<string, any>>;

export function SaveGame(arg1:models.SaveGameRequest):Promise<Record<string, any>>;

export function SaveManualGame(arg1:models.SaveGameRequest):Promise<Record<string, any>>;

export function TestConnections():Promise<main.ConnectionStatus>;

export function TestConnectionsWithConfig(arg1:main.ConfigData):Promise<main.ConnectionStatus>;

export function ValidateConfig():Promise<Record<string, any>>;
