// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAllPendingResults() {
  return window['go']['main']['App']['CheckAllPendingResults']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckGameResult(arg1) {
  return window['go']['main']['App']['CheckGameResult'](arg1);
}

export function ClearOldNotifications(arg1) {
  return window['go']['main']['App']['ClearOldNotifications'](arg1);
}

export function DeleteSavedGame(arg1) {
  return window['go']['main']['App']['DeleteSavedGame'](arg1);
}

export function GenerateStrategy(arg1) {
  return window['go']['main']['App']['GenerateStrategy'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetContestTemperatureAnalysis() {
  return window['go']['main']['App']['GetContestTemperatureAnalysis']();
}

export function GetCurrentConfig() {
  return window['go']['main']['App']['GetCurrentConfig']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDashboardSummary() {
  return window['go']['main']['App']['GetDashboardSummary']();
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetNextDraws() {
  return window['go']['main']['App']['GetNextDraws']();
}

export function GetNotifications(arg1, arg2) {
  return window['go']['main']['App']['GetNotifications'](arg1, arg2);
}

export function GetNumberFrequencyAnalysis(arg1) {
  return window['go']['main']['App']['GetNumberFrequencyAnalysis'](arg1);
}

export function GetPerformanceMetrics() {
  return window['go']['main']['App']['GetPerformanceMetrics']();
}

export function GetPredictorMetrics() {
  return window['go']['main']['App']['GetPredictorMetrics']();
}

export function GetROICalculator(arg1, arg2) {
  return window['go']['main']['App']['GetROICalculator'](arg1, arg2);
}

export function GetSavedGames(arg1) {
  return window['go']['main']['App']['GetSavedGames'](arg1);
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MarkNotificationAsRead(arg1) {
  return window['go']['main']['App']['MarkNotificationAsRead'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveGame(arg1) {
  return window['go']['main']['App']['SaveGame'](arg1);
}

export function SaveManualGame(arg1) {
  return window['go']['main']['App']['SaveManualGame'](arg1);
}

export function TestConnections() {
  return window['go']['main']['App']['TestConnections']();
}

export function TestConnectionsWithConfig(arg1) {
  return window['go']['main']['App']['TestConnectionsWithConfig'](arg1);
}

export function ValidateConfig() {
  return window['go']['main']['App']['ValidateConfig']();
}
