// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAllPendingResults() {
  return window['go']['main']['App']['CheckAllPendingResults']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckGameResult(arg1) {
  return window['go']['main']['App']['CheckGameResult'](arg1);
}

export function DebugClaudeConfig() {
  return window['go']['main']['App']['DebugClaudeConfig']();
}

export function DebugConfig() {
  return window['go']['main']['App']['DebugConfig']();
}

export function DebugSavedGamesDB() {
  return window['go']['main']['App']['DebugSavedGamesDB']();
}

export function DeleteSavedGame(arg1) {
  return window['go']['main']['App']['DeleteSavedGame'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function GenerateStrategy(arg1) {
  return window['go']['main']['App']['GenerateStrategy'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCurrentConfig() {
  return window['go']['main']['App']['GetCurrentConfig']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetNextDraws() {
  return window['go']['main']['App']['GetNextDraws']();
}

export function GetSavedGames(arg1) {
  return window['go']['main']['App']['GetSavedGames'](arg1);
}

export function GetSavedGamesStats() {
  return window['go']['main']['App']['GetSavedGamesStats']();
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveGame(arg1) {
  return window['go']['main']['App']['SaveGame'](arg1);
}

export function ScheduleUpdateCheck() {
  return window['go']['main']['App']['ScheduleUpdateCheck']();
}

export function TestConnections() {
  return window['go']['main']['App']['TestConnections']();
}

export function TestConnectionsWithConfig(arg1) {
  return window['go']['main']['App']['TestConnectionsWithConfig'](arg1);
}

export function ValidateConfig() {
  return window['go']['main']['App']['ValidateConfig']();
}
