// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DebugClaudeConfig():Promise<Record<string, any>>;

export function DebugConfig():Promise<Record<string, any>>;

export function GenerateStrategy(arg1:main.UserPreferences):Promise<main.StrategyResponse>;

export function GetCurrentConfig():Promise<main.ConfigData>;

export function GetDefaultConfig():Promise<main.ConfigData>;

export function GetNextDraws():Promise<Record<string, any>>;

export function GetStatistics():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function SaveConfig(arg1:main.ConfigData):Promise<Record<string, any>>;

export function TestConnections():Promise<main.ConnectionStatus>;

export function TestConnectionsWithConfig(arg1:main.ConfigData):Promise<main.ConnectionStatus>;

export function ValidateConfig():Promise<Record<string, any>>;
